version: "3.8"

services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - goals-net

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/goals
    depends_on:
      - mongodb
    networks:
      - goals-net

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - goals-net

networks:
  goals-net:
    driver: bridge
