apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongodb-port
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          command:
            - mongod
            - --replSet
            - rs0
            - --bind_ip_all
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
