apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-replica
spec:
  template:
    spec:
      containers:
        - name: mongo-init-replica
          image: mongo:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Sleeping 1 min to give time to pods to be running..."
              sleep 60
              echo "Awaken..."
              echo "Starting the job..."
              mongosh --host mongodb-statefulset-0.mongodb <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  {_id: 0, host: "mongodb-statefulset-0.mongodb:27017"},
                  {_id: 1, host: "mongodb-statefulset-1.mongodb:27017"},
                  {_id: 2, host: "mongodb-statefulset-2.mongodb:27017"}
                ]
              })
              EOF
              echo "Finishing the job..."
      restartPolicy: OnFailure
